apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: styu9t9ov-nodejs
  janus-idp.io/tekton: styu9t9ov-nodejs
  backstage.io/kubernetes-id: styu9t9ov-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: styu9t9ov-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
